### PR TITLE
PR for freertos static api usage in fsl_lpi2c

### PR DESCRIPTION
**Pull request by Hadatko**
Signed-off-by: Cervenka Dusan <cervenka@acrios.com>

**Prerequisites**
- [X] I have checked latest main branch and the issue still exists.
- [X] I did not see it is stated as known-issue in release notes.
- [X] No similar GitHub issue is related to this change.
- [ ] My code follows the commit guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.

**Describe the pull request**

#7 

Fixes # (issue)

**Type of change** (please delete options that are not relevant):

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Tests**

* Test configuration (please complete the following information):
   - Hardware setting:
   - Toolchain:
   - Test Tool preparation:
   - Any other dependencies:
* Test executed
  Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 
    - [X] Build Test
    - [X] Run Test

### CODE REVIEW

**Comment by mcuxsusan** [comment]
@Hadatko, again highly appreciate for your contribution. Linked the open issue since you have already build the PR.

**Comment by mcuxsusan** [comment]
@DavidJurajdaNXP, kind reminder, may you please help check the PR?

**Comment by Hadatko** [comment]
Hi, any news here?

**Comment by mcuxsusan** [comment]
Hi @Hadatko, thanks for your patience. @DavidJurajdaNXP, please help update your progress here.

**Comment by Hadatko** [comment]
:'(

**Comment by Hadatko** [comment]
@mcuxsusan Ping ;)

**Comment by Hadatko** [comment]
:'(

**Pull request closed without merging**
