### PR TITLE
devices: Add MIMX9352 support

### PR DESCRIPTION
**Pull request by LaurentiuM1234**
This PR contains the hand-picked commits from https://github.com/zephyrproject-rtos/hal_nxp/pull/213 that should have also been merged into the mcux-sdk repo.

### CODE REVIEW

**Comment by LaurentiuM1234** [comment]
FYI: @mmahadevan108 @JiafeiPan

Please review @mcuxsusan @yangbolu1991.

**Comment by JiafeiPan** [comment]
@LaurentiuM1234 , thanks for picking up these patches to mcux-sdk, but in fact these patches have already in our feature branch "feature/aarch64_support", according to our plan, these patches together with the other patches in branch "feature/aarch64_support" will be pushed to main branch after Harpoon release which is at the end of this month, so I suggest let's reject this PR currently and they will be pushed together with the other patches, so such we will have no conflictions, is it okay for you? and also would like to have @mcuxsusan 's comments, thanks.

**Comment by LaurentiuM1234** [comment]
> @LaurentiuM1234 , thanks for picking up these patches to mcux-sdk, but in fact these patches have already in our feature branch "feature/aarch64_support", according to our plan, these patches together with the other patches in branch "feature/aarch64_support" will be pushed to main branch after Harpoon release which is at the end of this month, so I suggest let's reject this PR currently and they will be pushed together with the other patches, so such we will have no conflictions, is it okay for you? and also would like to have @mcuxsusan 's comments, thanks.

Currently, I have 3 pending Zephyr/NXP HAL PRs which depend on this PR. Since these PRs have been in review for a while now I'd like to have this PR merged ASAP so I can take care of the others.

IMO this is already long overdue as it should have been taken care of before https://github.com/zephyrproject-rtos/hal_nxp/pull/213 was merged.

**Comment by mcuxsusan** [comment]
@LaurentiuM1234 , because Harpoon release is approaching and I believe these patches will be fully validated in Harpoon release cycle, let's just wait for @JiafeiPan's release launch(target end of this month) and let him make pr for these aarch64 support patches to our mcux-sdk main.

@JiafeiPan, I see in https://github.com/zephyrproject-rtos/hal_nxp/pull/213 you would like to merge this patches in Harpoon develop cycle directly to hal_nxp, this is not a suggest way for our NXP developer doing zephyr enablement for a new device. Now hal_nxp pulls mcux-sdk in to get the MCU/MPU drivers and devices support, if you would like to have this device support in zephyr in develop cycle, we strongly suggest you to make these PR to mcux-sdk main branch, then make a new pr to hal_nxp for updating, then hal_nxp no longer needs to maintain the patches in their own repo. @mmahadevan108, feel free to correct me if I am wrong.

**Comment by LaurentiuM1234** [comment]
It's been  3 weeks and as far as I can see this issue hasn't been solved. @JiafeiPan can I get an ETA of when you plan on addressing this?

**Comment by JiafeiPan** [comment]
@LaurentiuM1234 , I have created PR in NXP internal repo, and in review progress.

**Pull request closed without merging**
